Implement map before validation
WendellAdriel/laravel-validated-dto pull request #27
Opened 2023-05-04 15:12 UTC by Dennise89

2023-05-04 15:34 UTC, WendellAdriel requested changes
Please check the comments made

2023-05-04 15:34 UTC, WendellAdriel commented on src/ValidatedDTO.php
> +    private function parseData(?array $data): array
Rename this to parseDataBeforeInit

2023-05-04 15:34 UTC, WendellAdriel commented on src/ValidatedDTO.php
> +
Call the `mapBeforeValidation` here and assign to variable to avoid calling it multiple times

2023-05-04 15:34 UTC, WendellAdriel commented on src/ValidatedDTO.php
> +            $values[$key] = $value;
This can be a ternary instead

2023-05-04 15:34 UTC, WendellAdriel commented on src/ValidatedDTO.php
Some other things to work on:
1. Missing test cases
2. Missing the mapBeforeExport, are you going to work on this?
3. You need to run the linter to fix code styling issues

2023-05-08 13:45 UTC, WendellAdriel commented
I'm closing this one since the full implementation is on #29 
Thanks anyway for the help @Dennise89

2023-05-08 13:45 UTC, closed without merging

2023-05-10 07:06 UTC, Dennise89 commented on src/ValidatedDTO.php
@WendellAdriel Sorry for the late response, did not really have time to respond. I see you already resolved it, thanks for that!